import { FlatList, Pressable, ScrollView, StatusBar, StyleSheet } from 'react-native';
import { Text, View } from '@/components/Themed';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { Checkbox } from 'react-native-paper';

type subjectType = 'begining' | 'sustantives' | 'pronouns' | 'verbs' | 'questions' | 'conjunctions' | 'prepositions' | 'adverbs' | 'adjetives' | 'other' | 'compilation' | 'many' | 'various' | 'custom';

const arrayTopics: any[] = [
  { topic: 'custom', id: 0}, { topic: 'compilation', id: 1 }, { topic: 'sustantives', id: 2 }, { topic: 'pronouns', id: 3 }, { topic: 'verbs', id: 4 }, { topic: 'questions', id: 5 }, { topic: 'conjunctions', id: 6 }, { topic: 'prepositions', id: 7 }, { topic: 'adverbs', id: 8 }, { topic: 'adjetives', id: 9 }, { topic: 'other', id: 10 }, { topic: 'many', id: 11 }, { topic: 'various', id: 12 }
];

let wordSet = new Set<number>()

let reviewList: string

export default function TabOneScreen() {

  async function loadCustom(){
    const test = await AsyncStorage.getItem('custom');
    if (test) {
      custom = test.split(',') 
    } else {
      await AsyncStorage.setItem('custom', 'elsker med deg,make love to you');
    }
    const review = await AsyncStorage.getItem('review')
    if(review){
      reviewList = review
      console.log(reviewList)
    } else reviewList = ''
  }

  useFocusEffect(() => { loadCustom()})

  return (
    <View style={styles.main}>
      <StatusBar 
        barStyle={'light-content'}
        translucent={true} 
        backgroundColor="transparent"/>
      <TopicButtons/>
    </View>
  );
}

function TopicButtons() {
  type wordsTo = { word: string, index: number }
  const [topic, setTopic] = useState<subjectType>('begining');
  const [words, setWord] = useState<wordsTo>({ word: 'Select a Category', index: -1 })
  const [translate, setTranslate] = useState<string>('Waiting...')
  const [disabler, setDisabler] = useState<boolean>(false)
  const [show, setShow] = useState<boolean>(true)
  const [reviewState, setReviewState] = useState<string>('')
  const [lista2, setLista2] = useState<string[]>([])

  async function addReview(item: string) {
    reviewList = reviewList? reviewList.concat(',', item): item
    await AsyncStorage.setItem('review', reviewList)
    setReviewState(reviewList)
  }
  async function removeReview(item: string) {
    if(reviewList.endsWith(item)){
      reviewList = reviewList.replace(',' + item , '')
    } else if((reviewList.endsWith(item) && reviewList.startsWith(item)) || (reviewList.endsWith(item + ',') && reviewList.startsWith(item))){
      reviewList = ''
    } else {
      reviewList = reviewList.replace(item + ',' , '')
    }
    await AsyncStorage.setItem('review', reviewList)
    setReviewState(reviewList)
  }

  return (
    <View style={styles.container}>
      <View style={{...styles.horizontalContainer, backgroundColor: '#000'}}>
        <FlatList
          contentContainerStyle={styles.listContainer}
          data={arrayTopics}
          renderItem={({ item }) => (
            <Pressable onPress={() => {
              if (topic !== item.topic) {
                setTopic(item.topic)
                setWord(getWords(item.topic))
                wordSet.clear()
                setLista2([])
                setShow(true)
                setTranslate('Waiting...')
                setDisabler(false)
              }
            }}
              style={topic === item.topic ? styles.pressable : styles.pressable2}>
              <Text style={styles.text}>
                {item.topic}
              </Text>
            </Pressable>
          )}
          keyExtractor={item => item.id.toString()}
          horizontal={true}
        />
      </View>
      <View style={{...styles.contentContainer, backgroundColor: '#000'}}>
        <View style={{ flexDirection: 'column', backgroundColor: '#000' }}>
          <Text 
          style={[styles.display, words.index % 2 === 0? {color: 'blueviolet'}: {color: 'blue'}]}
          selectable={true}>
            {words.word}
          </Text>
          <Text 
          style={styles.translated}
          selectable={true}>
            {translate}
          </Text>
        </View>
        <View style={styles.show}>
          <Pressable style={[styles.showButton, disabler? {backgroundColor: 'green'} : {backgroundColor: 'blue'}]}
            disabled={disabler}
            android_ripple={{color: 'purple', borderless: false}}
            onPress={() => {
              if (topic !== 'begining') {
                setTranslate(showTranslated(topic, words.index));
                setDisabler(true)
              }
            }}>
              <Text>Show!</Text>
          </Pressable>
        </View>
      </View>
      <View style={{...styles.answears, backgroundColor: '#000'}}>
        <View style={{backgroundColor: '#000'}}>
          <Pressable style={[styles.button, disabler? {backgroundColor: 'blue'} : {backgroundColor: 'green'}]}
            android_ripple={{color: 'red', borderless: false}}
            disabled={!disabler}
            onPress={() => {
              if (topic !== 'begining') {
                setDisabler(false)
                setShow(false)
                if (words.index % 2 === 0) {
                  if (!wordSet.has(words.index + 1)) {
                    wordSet.add(words.index)
                  }
                } else if (!wordSet.has(words.index - 1)) {
                  wordSet.add(words.index)
                }
                setWord(getWords(topic))
                setTranslate('Waiting...')
              }
            }}>
            <Text>Wrong?</Text>
          </Pressable>
        </View>       
        <View style={{backgroundColor: '#000'}}>
          <Pressable style={[styles.button, disabler? {backgroundColor: 'blue'} : {backgroundColor: 'green'}]}
            android_ripple={{color: 'purple', borderless: false}}
            disabled={!disabler}
            onPress={() => {
              if (topic !== 'begining') {
                setWord(getWords(topic))
                setTranslate('Waiting...')
                setDisabler(false)
              }
            }}>
            <Text>Right?</Text>
          </Pressable>
        </View>
      </View>
      <View style={{backgroundColor: '#000', marginBottom: 12}}>
        <Pressable style={[styles.button, show? {backgroundColor: 'green'} : {backgroundColor: 'blue'}]}
          android_ripple={{color: 'gray', borderless: true}} 
          disabled={show}
          onPress={() => {
            setDisabler(false)
            setShow(true)
            const reviewList = Array.from(wordSet)
            setLista2(createList(topic, reviewList))
          }}><Text style={{ justifyContent: 'center', alignContent: 'center', fontSize: 16, color: 'white' }}>Review</Text>
        </Pressable>
      </View >
      <FlatList
        data={lista2}
        extraData={reviewState}
        renderItem={({ item, index }) => (
          <View style={{flexDirection: 'row', backgroundColor: '#000'}}>
            <Checkbox
              status={reviewList.includes(item)? 'checked': 'unchecked'}
              onPress={() => {
                if(!reviewList.includes(item)){
                  addReview(item)
                } else removeReview(item)
              }}
            ></Checkbox>
            <Text style={{color: '#fff'}}>{item}</Text>
          </View>
        )}>
      </FlatList>
    </View>
  );
}

const styles = StyleSheet.create({
  main: {
    flex: 1,
    paddingTop: StatusBar.currentHeight!,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#000',
    alignItems: 'center',
  },
  contentContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalContainer: {
    maxHeight: 50,
    marginTop: 10
  },
  listContainer: {
    flexGrow: 1,
    paddingHorizontal: 3
  },
  pressable: {
    margin: 5,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: 'gray',
  },
  pressable2: {
    margin: 5,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: 'blue',
  },
  text: {
    color: 'white',
    fontSize: 16,
  },
  display: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 30,
  },
  translated: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 30,
    color: 'white'
  },
  show: {
    marginTop: 20,
    borderRadius: 10,
    maxWidth: 120,
    fontSize: 30,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  showButton: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    fontSize: 30,
  },
  button: {
    marginHorizontal: 5,
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 20,
    fontSize: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  answears: {
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  failedList: {
    fontSize: 20,
    color: 'white',
    marginTop: 25,
    paddingHorizontal: 25,
    flexWrap: 'wrap'
  }
});

let currentIndex: number = 0
let testeIndex: number = -1
type wordsTo = { word: string, index: number }

function getWords(subject: subjectType): wordsTo {
  switch (subject) {
    case 'adjetives':
      currentIndex = Math.floor(Math.random() * adjetives.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: adjetives[currentIndex], index: currentIndex }

    case 'conjunctions':
      currentIndex = Math.floor(Math.random() * conjunctions.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: conjunctions[currentIndex], index: currentIndex }

    case 'adverbs':
      currentIndex = Math.floor(Math.random() * adverbs.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: adverbs[currentIndex], index: currentIndex }

    case 'other':
      currentIndex = Math.floor(Math.random() * other.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: other[currentIndex], index: currentIndex }

    case 'prepositions':
      currentIndex = Math.floor(Math.random() * prepositions.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: prepositions[currentIndex], index: currentIndex }

    case 'pronouns':
      currentIndex = Math.floor(Math.random() * pronouns.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: pronouns[currentIndex], index: currentIndex }

    case 'sustantives':
      currentIndex = Math.floor(Math.random() * sustantives.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: sustantives[currentIndex], index: currentIndex }

    case 'questions':
      currentIndex = Math.floor(Math.random() * questions.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: questions[currentIndex], index: currentIndex }

    case 'verbs':
      currentIndex = Math.floor(Math.random() * verbs.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: verbs[currentIndex], index: currentIndex }

    case 'various':
      currentIndex = Math.floor(Math.random() * various.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: various[currentIndex], index: currentIndex }

    case 'compilation':
      currentIndex = Math.floor(Math.random() * compilation.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: compilation[currentIndex], index: currentIndex }

    case 'many':
      currentIndex = Math.floor(Math.random() * many.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: many[currentIndex], index: currentIndex }

    case 'custom':
      currentIndex = Math.floor(Math.random() * custom.length)
      if (testeIndex !== currentIndex) {
        testeIndex = currentIndex
      } else return getWords(subject)

      return { word: custom[currentIndex], index: currentIndex }

    default:
      return { word: '', index: -1 }

  }
}

function showTranslated(subject: subjectType, index: number): string {
  switch (subject) {
    case 'adjetives':
      if (index % 2 === 0) {
        return adjetives[index + 1]
      } else return adjetives[index - 1]
    case 'adverbs':
      if (index % 2 === 0) {
        return adverbs[index + 1]
      } else return adverbs[index - 1]
    case 'conjunctions':
      if (index % 2 === 0) {
        return conjunctions[index + 1]
      } else return conjunctions[index - 1]
    case 'other':
      if (index % 2 === 0) {
        return other[index + 1]
      } else return other[index - 1]
    case 'prepositions':
      if (index % 2 === 0) {
        return prepositions[index + 1]
      } else return prepositions[index - 1]
    case 'pronouns':
      if (index % 2 === 0) {
        return pronouns[index + 1]
      } else return pronouns[index - 1]
    case 'questions':
      if (index % 2 === 0) {
        return questions[index + 1]
      } else return questions[index - 1]
    case 'sustantives':
      if (index % 2 === 0) {
        return sustantives[index + 1]
      } else return sustantives[index - 1]
    case 'verbs':
      if (index % 2 === 0) {
        return verbs[index + 1]
      } else return verbs[index - 1]
    case 'various':
      if (index % 2 === 0) {
        return various[index + 1]
      } else return various[index - 1]
    case 'compilation':
      if (index % 2 === 0) {
        return compilation[index + 1]
      } else return compilation[index - 1]
    case 'many':
      if (index % 2 === 0) {
        return many[index + 1]
      } else return many[index - 1]
    case 'custom':
      if (index % 2 === 0) {
        return custom[index + 1]
      } else return custom[index - 1]

    default:
      return ''
  }
}

function createList(topic: subjectType, lista: number[]): string[] {

  let items: string[] = [];

  for (let index of lista) {
    let currentItem: string = ''
    switch (topic) {
      case 'adjetives':
        currentItem = (index % 2 === 0)
          ? adjetives[index] + ': ' + adjetives[index + 1] + '\n'
          : adjetives[index - 1] + ': ' + adjetives[index] + '\n';
        break
      case 'adverbs':
        currentItem = (index % 2 === 0)
          ? adverbs[index] + ': ' + adverbs[index + 1] + '\n'
          : adverbs[index - 1] + ': ' + adverbs[index] + '\n';
        break
      case 'conjunctions':
        currentItem = (index % 2 === 0)
          ? conjunctions[index] + ': ' + conjunctions[index + 1] + '\n'
          : conjunctions[index - 1] + ': ' + conjunctions[index] + '\n';
        break
      case 'other':
        currentItem = (index % 2 === 0)
          ? other[index] + ': ' + other[index + 1] + '\n'
          : other[index - 1] + ': ' + other[index] + '\n';
        break
      case 'prepositions':
        currentItem = (index % 2 === 0)
          ? prepositions[index] + ': ' + prepositions[index + 1] + '\n'
          : prepositions[index - 1] + ': ' + prepositions[index] + '\n';
        break
      case 'pronouns':
        currentItem = (index % 2 === 0)
          ? pronouns[index] + ': ' + pronouns[index + 1] + '\n'
          : pronouns[index - 1] + ': ' + pronouns[index] + '\n';
        break
      case 'questions':
        currentItem = (index % 2 === 0)
          ? questions[index] + ': ' + questions[index + 1] + '\n'
          : questions[index - 1] + ': ' + questions[index] + '\n';
        break
      case 'sustantives':
        currentItem = (index % 2 === 0)
          ? sustantives[index] + ': ' + sustantives[index + 1] + '\n'
          : sustantives[index - 1] + ': ' + sustantives[index] + '\n';
        break
      case 'verbs':
        currentItem = (index % 2 === 0)
          ? verbs[index] + ': ' + verbs[index + 1] + '\n'
          : verbs[index - 1] + ': ' + verbs[index] + '\n';
        break
      case 'various':
        currentItem = (index % 2 === 0)
          ? various[index] + ': ' + various[index + 1] + '\n'
          : various[index - 1] + ': ' + various[index] + '\n';
        break
      case 'compilation':
        currentItem = (index % 2 === 0)
          ? compilation[index] + ': ' + compilation[index + 1] + '\n'
          : compilation[index - 1] + ': ' + compilation[index] + '\n';
        break
      case 'many':
        currentItem = (index % 2 === 0)
          ? many[index] + ': ' + many[index + 1] + '\n'
          : many[index - 1] + ': ' + many[index] + '\n';
        break
      case 'custom':
        currentItem = (index % 2 === 0)
          ? custom[index] + ': ' + custom[index + 1] + '\n'
          : custom[index - 1] + ': ' + custom[index] + '\n';
        break

      default:
        currentItem = ''
        break
    }
    items.push(currentItem);

  }
  return items
}

let custom: string[] = [
  'elsker med deg', 'make love to you'
]

const sustantives: string[] = [
  '(et) år', '(a) year',
  '(en) dag', '(a) day',
  '(en) kveld', 'an evening',
  '(et) barn', 'a child',
  '(ei, en) mor', 'a mother',
  '(en) far', 'a father',
  '(en) mann', 'a man',
  '(ei, en) kvinne', 'a woman',
  '(ei, en) jente', 'a girl',
  '(en) gutt', 'a boy',
  '(en) gang', 'sometime',
  '(et) liv', 'a life',
  '(en) del', 'a part',
  '(en) ting', 'a thing',
  '(en) grunn', 'a cause',
  '(et) sted', 'a place, a spot',
  '(et) hus', 'a house',
  '(en) skole', 'a school',
  '(en) by', 'a city',
  '(et) land', 'a country',
  '(en) plass', 'a square; a seat',
  '(en) vei', 'a way; a path',
  '(en) side', 'a side; a page',
  '(et) ord', 'a word',
  '(et) par', 'a pair; a couple',
  '(en) kunde', 'a customer',
  '(et) forhold', 'a relationship',
  '(et) foto', 'a photo',
  '(et) hode', 'a head',
  '(et) ansikt', 'a face',
  '(en, ei) hånd', 'a hand',
  '(et) øye', 'an eye',
  '(et) møte', 'a meeting',
  '(et) mål', 'an aim; a goal',
  '(en) seier', 'a victory, a win',
  '(en) måte', 'manner, way (of doing things)',
  '(en) sak', 'issue, matter, business (concern)',
  '(et) arbeid', 'work',
  '(en, ei) stund', 'a moment; a while',
  '(en) hjelp', 'help',
  '(et) spørsmål', 'a question',
  '(en) regjering', 'a government',
  '(et) eksempel', 'an example',
  '(en) kamp', 'fight, battle; a match',
  '(en, ei) dør', 'a door',
  '(en) slutt', 'end',
  'alle', 'all',
  'alt', 'everything',
  'tid', 'time',
  'krone', 'krone (currency); a crown',
  'menneske', 'person',
  'mennesker', 'people',
  'verden', 'world',
  'prosent', 'percent',
  'penger', 'money',
  'politi', '(n) police',
  'meter', 'meter'
]

const pronouns: string[] = [
  'jeg', 'I',
  'du', 'you',
  'han', 'he',
  'hun', 'she',
  'vi', 'we',
  'dere', 'you (plural)',
  'de', 'they',
  'noen', 'someone',
  'noe', 'something',
  'ingenting', 'nothing',
  'ingen', 'no one',
  'selv', 'myself; oneself',
  'alle', 'all, everyone',
  'hver', 'every',
  'hverandre', 'each other',
  'denne', 'this',
  'man', 'one (person)'
]

const verbs: string[] = [
  'å begynne', 'to start; to begin',
  'å bety', 'to mean',
  'å bli', 'to become; to stay',
  'å bruke', 'to use',
  'å burde', 'should',
  'å finne', 'to find',
  'å fortelle', 'to tell',
  'å føle', 'to feel',
  'å følge', 'to follow',
  'å få', 'to get, to receive',
  'å gi', 'to give',
  'å gjelde', 'to concern, to regard (sb/sth)',
  'å gjøre', 'to do',
  'å gå', 'to walk, go on foot',
  'å ha', 'to have',
  'å hjelpe', 'to help',
  'å holde', 'to hold; to keep',
  'å høre', 'to hear, to listen',
  'å kjenne', 'to know, to be familiar with',
  'å komme', 'to come, to arrive',
  'å kunne', 'can',
  'å lage', 'to make',
  'å late', 'to pretend',
  'å le', 'to laugh',
  'å legge', 'to put down; to lay; to put',
  'å ligge', 'to lie (be located)',
  'å like', 'to like',
  'å mene', 'to think; to mean (have in mind)',
  'å måtte', 'must; have to',
  'å rekke', 'to manage (have the time to), to catch',
  'å se', 'to see',
  'å sette', 'to put; to arrange',
  'å si', 'to say',
  'å skulle', 'would; be supposed to',
  'å slutte', 'to end, to stop',
  'å slå', 'to beat; to hit; to strike',
  'å snakke', 'to talk',
  'å spørre', 'to ask',
  'å stå', 'to stand',
  'å svare', 'to answer',
  'å synes', 'to think, to have an opinion',
  'å ta', 'to take',
  'å tenke', 'to think',
  'å trenge', 'to need',
  'å tro', 'to believe; to have an opinion',
  'å vente', 'to wait',
  'å ville', 'to want; would (like)',
  'å vise', 'to show',
  'å vite', 'to know',
  'å være', 'to be',
  'å ønske', 'to wish (to desire)',
  'det finnes', 'there is/there are'
]

const questions: string[] = [
  'Hva?/hva', 'What?/what',
  'Hvem?/hvem', 'Who?/who',
  'Hvor?/hvor', 'Where?/where',
  'Hvordan?/hvordan', 'How?/how',
  'Hvorfor?/hvorfor', 'Why?/why',
  'Når?/når', 'When?/when'
]

const conjunctions: string[] = [
  'altså', 'so',
  'at', 'that',
  'både', 'both',
  'dersom', 'if, whether',
  'eller', 'or',
  'enda (mer)', 'even (more)',
  'enn', 'than',
  'fordi', 'because',
  'hvis/om', 'if',
  'men', 'but',
  'og', 'and',
  'siden', 'since',
  'som', 'that, like',
]

const prepositions: string[] = [
  'i', 'in',
  'på', 'in/on/at',
  'ved', 'at, next to, near',
  'til', 'to; until',
  'mot', 'towards',
  'fra', 'from',
  'av', 'by (sb); of; from',
  'for', 'for',
  'med', 'with',
  'uten', 'without',
  'om', 'about',
  'etter', 'after',
  'over', 'above',
  'under', 'under; below',
  'mellom', 'between',
  'foran', 'in front of',
  'bak', 'behind',
  'overfor', 'opposite, across',
  'utenfor', 'out of; outside',
  'omkring', 'around, round',
  'hos', 'at',
  'rundt', 'about, roughly',
  'gjennom', 'through; via',
  'blant', 'among'
]

const adverbs: string[] = [
  'ikke', 'not',
  'så', 'so',
  'også', 'also',
  'inn', 'in; inside; into',
  'ut', 'out, outside',
  'heller', 'rather',
  'likevel', 'nevertheless; anyway',
  'slik', 'like that; so; such',
  'mer', 'more',
  'mindre', 'less',
  'først', 'first',
  'sammen', 'together',
  'alene', 'alone',
  'nå', 'now',
  'da', 'then',
  'bare', 'only, just',
  'opp', 'up, upwards (direction)',
  'oppe', 'up, upstairs (location)',
  'ned', 'down, downwards',
  'der', 'there',
  'her', 'here',
  'før', 'before',
  'igjen', 'again',
  'helt', 'completely',
  'litt', 'a little (bit)',
  'nok', 'enough',
  'alltid', 'always',
  'aldri', 'never',
  'ofte', 'often',
  'kanskje', 'possibly, maybe',
  'mye', 'a lot; much',
  'rundt', 'around',
  'tilbake', 'back',
  'mens', 'while; whereas',
  'derfor', 'therefore, that’s why',
  'fram', 'forward',
  'lenge', 'long (about time)',
  'nesten', 'almost',
  'frem', 'ahead',
  'bak', 'at the back',
  'bort', 'away',
  'mest', 'the most',
  'tidligere', 'earlier, sooner, before',
  'senere', 'later',
  'samtidig', 'at the same time, simultaneously',
  'meget', 'very',
  'lite', 'little (not much)',
  'ikke ennå', 'not yet',
  'allerede', 'already, yet (in questions)',
  'inne', 'indoors, inside',
  'ute', 'outside, outdoors',
  'hjem', 'home (direction)',
  'hjemme', 'home',
  'lenger', 'further, farther',
  'særlig', 'especially, particularly',
  'akkurat', 'just, just right, precisely',
  'borte', 'away',
  'plutselig', 'suddenly, all of a sudden',
  'snart', 'soon, before long',
  'svært', 'very, a lot',
  'dessuten', 'moreover',
  'gjerne', 'willingly',
  'imidlertid', 'however',
  'dermed', 'thus',
  'bra', 'fine, well',
  'sikkert', 'surely, certainly',
  'virkelig', 'really, indeed',
  'ganske', 'quite',
  'ellers', 'otherwise',
  'minst', 'at least, minimum',
  'fortsatt', 'still',
  'stadig', 'constantly, all the time',
  'visst', 'surely, certainly',
  'fremdeles', 'still',
  'imot', 'against',
  'helst', 'preferably',
  'nettopp', 'just',
  'nærmere', 'closer'
]

const adjetives: string[] = [
  'ny', 'new',
  'gammel', 'old',
  'ung', 'young',
  'god', 'good',
  'bedre', 'better',
  'dårlig', 'bad',
  'mange', 'many',
  'flere', 'more',
  'få', 'few',
  'stor', 'big',
  'liten', 'little',
  'lang', 'long',
  'kort', 'short',
  'kjent', 'known, famous',
  'fast', 'permanent',
  'lett', 'easy',
  'vanskelig', 'difficult',
  'full', 'full',
  'hel', 'complete, whole',
  'glad', 'happy',
  'viktig', 'important',
  'redd', 'scared',
  'sterk', 'strong',
  'vant', 'used',
  'neste', 'next',
  'videre', 'farther; further',
  'sist', 'last',
  'rett', 'right, correct',
  'riktig', 'correct',
  'tidlig', 'early',
  'mulig', 'possible',
  'klar', 'ready; clear (meaning); bright (light)',
  '(de) andre', '(the) others',
  'annen', 'another',
  'egen', 'one’s own',
  'enkelt', 'individual; simple',
  'eneste', '(the) only (one)',
]

const other: string[] = [
  'jo', 'yes (to a negative question)',
  'samme', 'the same',
  'begge', 'both',
  'egentlig', 'actually, in fact',
  'de fleste', 'majority, most',
  'en/et slags', 'some (kind of)',
  'i løpet av', 'during',
  'i tillegg', 'in addition',
  'til slutt', 'finally; in the end',
  'av og til', 'sometimes',
  'i dag', 'today',
  'i går', 'yesterday',
  'i fjor', 'last year',
  'å bli med', 'to come along',
  'for å', 'in order to',
  'på grunn av', 'due to, because of'
]

const many: string[] = [
  'lillesøster', 'younger sister',
  'lillebror', 'younger brother', 'niese', 'niece',
  'søskenbarn', 'cousin', 'svoger', 'brother-in-law',
  'svigermor', 'mother-in-law', 'svigerfar', 'father-in-law', 'oldefar', 'great-grandfather',
  'svigerinne', 'sister-in-law', 'nevø', 'nephew', 'storebror', 'older brother',
  'oldemor', 'great-grandmother',
  'sint', 'angry', 'rolig', 'calm', 'ensom', 'lonely',
  'høflig', 'polite', 'smart', 'clever', 'ærlig', 'honest',
  'irriterende', 'annoying', 'stolt', 'proud',
  'smal', 'narrow', 'hard', 'hard',
  'myk', 'soft', 'lett', 'light', 'billig', 'cheap',
  'dyr', 'expensive', 'opptatt', 'busy', 'solrik', 'sunny',
  'regnete', 'rainy', 'fuktig', 'humid', 'vindfullt', 'windy',
  'overskyet', 'cloudy', 'sunn', 'healthy',
  'høy', 'tall', 'vakker', 'beautiful',
  'kjølig', 'cool', 'stygg', 'ugly', 'snill', 'kind',
  'skummelt', 'scary', 'enkel', 'easy', 'ren', 'clean',
  'skitten', 'dirty', 'nær', 'near', 'trøtt', 'tired',
  'fattig', 'poor', 'lav', 'low',
  'høy', 'high', 'berømt', 'famous',
  'svinekjøtt', 'pork', 'sekund', 'second', 'kjøkken', 'kitchen',
  'bad', 'bathroom', 'datamaskin', 'computer',
  'seng', 'bed', 'sofa', 'sofa',
  'fisk', 'fish', 'sykepleier', 'nurse',
  'is', 'ice', 'storfekjøtt', 'beef', 'voksen', 'adult',
  'regn', 'rain', 'sky', 'cloud',
  'lærer', 'teacher', 'skjorte', 'shirt',
  'sokk', 'sock', 'bukse', 'pants', 'venn', 'friend',
  'hvile', 'rest',
  'lage mat', 'cook',
  'komme hjem', 'return',
  'bade', 'bathe',
  'sove', 'sleep',
  'våkne', 'wake up',
  'tegne', 'draw',
  'skru på', 'turn on',
  'ankomme', 'arrive',
  'svare', 'answer',
  'undervise', 'teach',
  'ta imot', 'receive',
  'planlegge', 'plan',
  'forklare', 'explain',
  'lukke', 'close',
  'kjøpe', 'buy',
  'løpe', 'run',
  'ville ha', 'want',
  'lese', 'read',
  'se etter', 'search',
  'omvisning', 'tour',
  'sette', 'put',
  'bruke', 'use',
  'sitte', 'ride',
  'avlyse', 'cancel',
  'ringe', 'call',
  'huske', 'remember',
  'lage', 'make',
  'reise', 'travel',
  'pusse', 'brush',
  'dusje', 'shower',
  'vaske', 'wash',
  'snakke', 'talk',
  'åpne', 'open',
  'bli ferdig', 'finish',
  'se', 'watch',
  'studere', 'study',
  'dø', 'die',
  'vente', 'wait'
]

const compilation: string[] = [
  '(et) år', '(a) year',
  '(en) dag', '(a) day',
  '(en) kveld', 'an evening',
  '(et) barn', 'a child',
  '(ei, en) mor', 'a mother',
  '(en) far', 'a father',
  '(en) mann', 'a man',
  '(ei, en) kvinne', 'a woman',
  '(ei, en) jente', 'a girl',
  '(en) gutt', 'a boy',
  '(en) gang', 'sometime',
  '(et) liv', 'a life',
  '(en) del', 'a part',
  '(en) ting', 'a thing',
  '(en) grunn', 'a cause',
  '(et) sted', 'a place, a spot',
  '(et) hus', 'a house',
  '(en) skole', 'a school',
  '(en) by', 'a city',
  '(et) land', 'a country',
  '(en) plass', 'a square; a seat',
  '(en) vei', 'a way; a path',
  '(en) side', 'a side; a page',
  '(et) ord', 'a word',
  '(et) par', 'a pair; a couple',
  '(en) kunde', 'a customer',
  '(et) forhold', 'a relationship',
  '(et) foto', 'a photo',
  '(et) hode', 'a head',
  '(et) ansikt', 'a face',
  '(en, ei) hånd', 'a hand',
  '(et) øye', 'an eye',
  '(et) møte', 'a meeting',
  '(et) mål', 'an aim; a goal',
  '(en) seier', 'a victory, a win',
  '(en) måte', 'manner, way (of doing things)',
  '(en) sak', 'issue, matter, business (concern)',
  '(et) arbeid', 'work',
  '(en, ei) stund', 'a moment; a while',
  '(en) hjelp', 'help',
  '(et) spørsmål', 'a question',
  '(en) regjering', 'a government',
  '(et) eksempel', 'an example',
  '(en) kamp', 'fight, battle; a match',
  '(en, ei) dør', 'a door',
  '(en) slutt', 'end',
  'alle', 'all',
  'alt', 'everything',
  'tid', 'time',
  'krone', 'krone (currency); a crown',
  'menneske', 'person',
  'mennesker', 'people',
  'verden', 'world',
  'prosent', 'percent',
  'penger', 'money',
  'politi', '(n) police',
  'meter', 'meter',
  'jeg', 'I',
  'du', 'you',
  'han', 'he',
  'hun', 'she',
  'vi', 'we',
  'dere', 'you (plural)',
  'de', 'they',
  'noen', 'someone',
  'noe', 'something',
  'ingenting', 'nothing',
  'ingen', 'no one',
  'selv', 'myself; oneself',
  'alle', 'all, everyone',
  'hver', 'every',
  'hverandre', 'each other',
  'denne', 'this',
  'man', 'one (person)',
  'å begynne', 'to start; to begin',
  'å bety', 'to mean',
  'å bli', 'to become; to stay',
  'å bruke', 'to use',
  'å burde', 'should',
  'å finne', 'to find',
  'å fortelle', 'to tell',
  'å føle', 'to feel',
  'å følge', 'to follow',
  'å få', 'to get, to receive',
  'å gi', 'to give',
  'å gjelde', 'to concern, to regard (sb/sth)',
  'å gjøre', 'to do',
  'å gå', 'to walk, go on foot',
  'å ha', 'to have',
  'å hjelpe', 'to help',
  'å holde', 'to hold; to keep',
  'å høre', 'to hear, to listen',
  'å kjenne', 'to know, to be familiar with',
  'å komme', 'to come, to arrive',
  'å kunne', 'can',
  'å lage', 'to make',
  'å late', 'to pretend',
  'å le', 'to laugh',
  'å legge', 'to put down; to lay; to put',
  'å ligge', 'to lie (be located)',
  'å like', 'to like',
  'å mene', 'to think; to mean (have in mind)',
  'å måtte', 'must; have to',
  'å rekke', 'to manage (have the time to), to catch',
  'å se', 'to see',
  'å sette', 'to put; to arrange',
  'å si', 'to say',
  'å skulle', 'would; be supposed to',
  'å slutte', 'to end, to stop',
  'å slå', 'to beat; to hit; to strike',
  'å snakke', 'to talk',
  'å spørre', 'to ask',
  'å stå', 'to stand',
  'å svare', 'to answer',
  'å synes', 'to think, to have an opinion',
  'å ta', 'to take',
  'å tenke', 'to think',
  'å trenge', 'to need',
  'å tro', 'to believe; to have an opinion',
  'å vente', 'to wait',
  'å ville', 'to want; would (like)',
  'å vise', 'to show',
  'å vite', 'to know',
  'å være', 'to be',
  'å ønske', 'to wish (to desire)',
  'det finnes', 'there is/there are',
  'Hva?/hva', 'What?/what',
  'Hvem?/hvem', 'Who?/who',
  'Hvor?/hvor', 'Where?/where',
  'Hvordan?/hvordan', 'How?/how',
  'Hvorfor?/hvorfor', 'Why?/why',
  'Når?/når', 'When?/when',
  'altså', 'so',
  'at', 'that',
  'både', 'both',
  'dersom', 'if, whether',
  'eller', 'or',
  'enda (mer)', 'even (more)',
  'enn', 'than',
  'fordi', 'because',
  'hvis/om', 'if',
  'men', 'but',
  'og', 'and',
  'siden', 'since',
  'som', 'that, like',
  'i', 'in',
  'på', 'in/on/at',
  'ved', 'at, next to, near',
  'til', 'to; until',
  'mot', 'towards',
  'fra', 'from',
  'av', 'by (sb); of; from',
  'for', 'for',
  'med', 'with',
  'uten', 'without',
  'om', 'about',
  'etter', 'after',
  'over', 'above',
  'under', 'under; below',
  'mellom', 'between',
  'foran', 'in front of',
  'bak', 'behind',
  'overfor', 'opposite, across',
  'utenfor', 'out of; outside',
  'omkring', 'around, round',
  'hos', 'at',
  'rundt', 'about, roughly',
  'gjennom', 'through; via',
  'blant', 'among',
  'ikke', 'not',
  'så', 'so',
  'også', 'also',
  'inn', 'in; inside; into',
  'ut', 'out, outside',
  'heller', 'rather',
  'likevel', 'nevertheless; anyway',
  'slik', 'like that; so; such',
  'mer', 'more',
  'mindre', 'less',
  'først', 'first',
  'sammen', 'together',
  'alene', 'alone',
  'nå', 'now',
  'da', 'then',
  'bare', 'only, just',
  'opp', 'up, upwards (direction)',
  'oppe', 'up, upstairs (location)',
  'ned', 'down, downwards',
  'der', 'there',
  'her', 'here',
  'før', 'before',
  'igjen', 'again',
  'helt', 'completely',
  'litt', 'a little (bit)',
  'nok', 'enough',
  'alltid', 'always',
  'aldri', 'never',
  'ofte', 'often',
  'kanskje', 'possibly, maybe',
  'mye', 'a lot; much',
  'rundt', 'around',
  'tilbake', 'back',
  'mens', 'while; whereas',
  'derfor', 'therefore, that’s why',
  'fram', 'forward',
  'lenge', 'long (about time)',
  'nesten', 'almost',
  'frem', 'ahead',
  'bak', 'at the back',
  'bort', 'away',
  'mest', 'the most',
  'tidligere', 'earlier, sooner, before',
  'senere', 'later',
  'samtidig', 'at the same time, simultaneously',
  'meget', 'very',
  'lite', 'little (not much)',
  'ikke ennå', 'not yet',
  'allerede', 'already, yet (in questions)',
  'inne', 'indoors, inside',
  'ute', 'outside, outdoors',
  'hjem', 'home (direction)',
  'hjemme', 'home',
  'lenger', 'further, farther',
  'særlig', 'especially, particularly',
  'akkurat', 'just, just right, precisely',
  'borte', 'away',
  'plutselig', 'suddenly, all of a sudden',
  'snart', 'soon, before long',
  'svært', 'very, a lot',
  'dessuten', 'moreover',
  'gjerne', 'willingly',
  'imidlertid', 'however',
  'dermed', 'thus',
  'bra', 'fine, well',
  'sikkert', 'surely, certainly',
  'virkelig', 'really, indeed',
  'ganske', 'quite',
  'ellers', 'otherwise',
  'minst', 'at least, minimum',
  'fortsatt', 'still',
  'stadig', 'constantly, all the time',
  'visst', 'surely, certainly',
  'fremdeles', 'still',
  'imot', 'against',
  'helst', 'preferably',
  'nettopp', 'just',
  'nærmere', 'closer',
  'ny', 'new',
  'gammel', 'old',
  'ung', 'young',
  'god', 'good',
  'bedre', 'better',
  'dårlig', 'bad',
  'mange', 'many',
  'flere', 'more',
  'få', 'few',
  'stor', 'big',
  'liten', 'little',
  'lang', 'long',
  'kort', 'short',
  'kjent', 'known, famous',
  'fast', 'permanent',
  'lett', 'easy',
  'vanskelig', 'difficult',
  'full', 'full',
  'hel', 'complete, whole',
  'glad', 'happy',
  'viktig', 'important',
  'redd', 'scared',
  'sterk', 'strong',
  'vant', 'used',
  'neste', 'next',
  'videre', 'farther; further',
  'sist', 'last',
  'rett', 'right, correct',
  'riktig', 'correct',
  'tidlig', 'early',
  'mulig', 'possible',
  'klar', 'ready; clear (meaning); bright (light)',
  '(de) andre', '(the) others',
  'annen', 'another',
  'egen', 'one’s own',
  'enkelt', 'individual; simple',
  'eneste', '(the) only (one)',
  'jo', 'yes (to a negative question)',
  'samme', 'the same',
  'begge', 'both',
  'egentlig', 'actually, in fact',
  'de fleste', 'majority, most',
  'en/et slags', 'some (kind of)',
  'i løpet av', 'during',
  'i tillegg', 'in addition',
  'til slutt', 'finally; in the end',
  'av og til', 'sometimes',
  'i dag', 'today',
  'i går', 'yesterday',
  'i fjor', 'last year',
  'å bli med', 'to come along',
  'for å', 'in order to',
  'på grunn av', 'due to, because of',
  'lillesøster', 'younger sister',
  'lillebror', 'younger brother', 'niese', 'niece',
  'søskenbarn', 'cousin', 'svoger', 'brother-in-law',
  'svigermor', 'mother-in-law', 'svigerfar', 'father-in-law', 'oldefar', 'great-grandfather',
  'svigerinne', 'sister-in-law', 'nevø', 'nephew', 'storebror', 'older brother',
  'oldemor', 'great-grandmother',
  'sint', 'angry', 'rolig', 'calm', 'ensom', 'lonely',
  'høflig', 'polite', 'smart', 'clever', 'ærlig', 'honest',
  'irriterende', 'annoying', 'stolt', 'proud',
  'smal', 'narrow', 'hard', 'hard',
  'myk', 'soft', 'lett', 'light', 'billig', 'cheap',
  'dyr', 'expensive', 'opptatt', 'busy', 'solrik', 'sunny',
  'regnete', 'rainy', 'fuktig', 'humid', 'vindfullt', 'windy',
  'overskyet', 'cloudy', 'sunn', 'healthy',
  'høy', 'tall', 'vakker', 'beautiful',
  'kjølig', 'cool', 'stygg', 'ugly', 'snill', 'kind',
  'skummelt', 'scary', 'enkel', 'easy', 'ren', 'clean',
  'skitten', 'dirty', 'nær', 'near', 'trøtt', 'tired',
  'fattig', 'poor', 'lav', 'low',
  'høy', 'high', 'berømt', 'famous',
  'svinekjøtt', 'pork', 'sekund', 'second', 'kjøkken', 'kitchen',
  'bad', 'bathroom', 'datamaskin', 'computer',
  'seng', 'bed', 'sofa', 'sofa',
  'fisk', 'fish', 'sykepleier', 'nurse',
  'is', 'ice', 'storfekjøtt', 'beef', 'voksen', 'adult',
  'regn', 'rain', 'sky', 'cloud',
  'lærer', 'teacher', 'skjorte', 'shirt',
  'sokk', 'sock', 'bukse', 'pants', 'venn', 'friend',
  'hvile', 'rest',
  'lage mat', 'cook',
  'komme hjem', 'return',
  'bade', 'bathe',
  'sove', 'sleep',
  'våkne', 'wake up',
  'tegne', 'draw',
  'skru på', 'turn on',
  'ankomme', 'arrive',
  'svare', 'answer',
  'undervise', 'teach',
  'ta imot', 'receive',
  'planlegge', 'plan',
  'forklare', 'explain',
  'lukke', 'close',
  'kjøpe', 'buy',
  'løpe', 'run',
  'ville ha', 'want',
  'lese', 'read',
  'se etter', 'search',
  'omvisning', 'tour',
  'sette', 'put',
  'bruke', 'use',
  'sitte', 'ride',
  'avlyse', 'cancel',
  'ringe', 'call',
  'huske', 'remember',
  'lage', 'make',
  'reise', 'travel',
  'pusse', 'brush',
  'dusje', 'shower',
  'vaske', 'wash',
  'snakke', 'talk',
  'åpne', 'open',
  'bli ferdig', 'finish',
  'se', 'watch',
  'studere', 'study',
  'dø', 'die',
  'vente', 'wait',
  'jeg', 'I',
  'det', 'it',
  'er', 'am',
  'du', 'you',
  'ikke', 'not',
  'en', 'an',
  'og', 'and',
  'i', 'in',
  'har', 'have',
  'vi', 'we',
  'på', 'on',
  'til', 'to',
  'med', 'with',
  'han', 'he',
  'deg', 'you',
  'for', 'for',
  'meg', 'me',
  'hva', 'what',
  'at', 'at',
  'den', 'it',
  'så', 'so',
  'som', 'as',
  'de', 'they',
  'kan', 'can',
  'var', 'was',
  'vil', 'will',
  'av', 'of',
  'skal', 'shall',
  'om', 'if',
  'men', 'but',
  'et', 'an',
  'her', 'here',
  'ja', 'yes',
  'bare', 'only',
  'dere', 'you (plural)',
  'hun', 'she',
  'må', 'must',
  'noe', 'something',
  'ham', 'him',
  'dette', 'this',
  'nei', 'no',
  'nå', 'now',
  'kom', 'come',
  'min', 'my',
  'vet', 'know',
  'der', 'there',
  'din', 'your',
  'ut', 'out',
  'hvor', 'where',
  'da', 'when',
  'fra', 'from',
  'oss', 'us',
  'se', 'see',
  'være', 'be',
  'ha', 'have',
  'dem', 'them',
  'gjør', 'do',
  'igjen', 'again',
  'noen', 'some',
  'kommer', 'come',
  'ta', 'take',
  'ville', 'would',
  'hvis', 'if',
  'alle', 'all',
  'få', 'get',
  'hvorfor', 'why',
  'tror', 'think',
  'går', 'yesterday',
  'alt', 'everything',
  'opp', 'up',
  'sa', 'said',
  'hvordan', 'how',
  'gå', 'go',
  'ingen', 'no',
  'når', 'when',
  'eller', 'or',
  'hvem', 'who',
  'får', 'get',
  'seg', 'themselves',
  'la', 'let',
  'blir', 'becomes',
  'ser', 'see',
  'takk', 'thanks',
  'gjøre', 'do',
  'bli', 'be',
  'bra', 'good',
  'hadde', 'had',
  'si', 'say',
  'denne', 'this',
  'henne', 'her',
  'litt', 'little',
  'inn', 'In',
  'jo', 'yes',
  'etter', 'after',
  'kunne', 'could',
  'vel', 'well',
  'to', 'two',
  'skulle', 'should',
  'ved', 'by',
  'aldri', 'never',
  'hei', 'hi',
  'over', 'over',
  'god', 'good',
  'tilbake', 'back',
  'kanskje', 'perhaps',
  'man', 'one',
  'også', 'also',
  'ble', 'was',
  'nok', 'enough',
  'sier', 'says',
  'selv', 'even',
  'hva', 'what',
  'før', 'before',
  'godt', 'well',
  'ok', 'ok',
  'sammen', 'together',
  'ned', 'down',
  'gi', 'provide',
  'hans', 'his',
  'gang', 'time',
  'dag', 'day',
  'tar', 'takes',
  'mer', 'more',
  'trenger', 'need',
  'mine', 'mine',
  'vært', 'been',
  'mitt', 'my',
  'mye', 'much',
  'helt', 'completely',
  'andre', 'second',
  'sett', 'seen',
  'vær', 'weather',
  'gjorde', 'did',
  'hele', 'throughout',
  'siden', 'ago',
  'komme', 'come',
  'enn', 'than',
  'deres', 'yours (plural)',
  'år', 'year',
  'ditt', 'your',
  'mann', 'husband',
  'hold', 'hold',
  'mr', 'Mr.',
  'mener', 'mean',
  'fikk', 'received',
  'mot', 'against',
  'vent', 'wait',
  'dine', 'your',
  'far', 'father',
  'fordi', 'because',
  'faen', 'fuck',
  'mange', 'many',
  'snakke', 'talk',
  'tre', 'three',
  'hjem', 'home',
  'ting', 'things',
  'gjort', 'made',
  'liker', 'like',
  'sant', 'true',
  'folk', 'people',
  'greit', 'okay',
  'alltid', 'always',
  'rett', 'right',
  'sånn', 'like',
  'tid', 'time',
  'dra', 'go',
  'unnskyld', 'pardon',
  'morgen', 'morning',
  'sir', 'sir',
  'virkelig', 'really',
  'elsker', 'love',
  'bedre', 'better',
  'veldig', 'very',
  'tok', 'took',
  'hit', 'here',
  'vår', 'spring',
  'uten', 'without',
  'mor', 'mother',
  'står', 'stands',
  'kveld', 'evening',
  'død', 'death',
  'burde', 'should',
  'snakker', 'speaks',
  'livet', 'life',
  'finne', 'find',
  'gikk', 'went',
  'sin', 'its',
  'gud', 'god',
  'beklager', 'sorry',
  'trodde', 'thought',
  'ingenting', 'nothing',
  'hør', 'listen',
  'akkurat', 'right',
  'kjenner', 'know',
  'første', 'first',
  'sted', 'place',
  'disse', 'these',
  'ute', 'out',
  'slik', 'so',
  'samme', 'same',
  'klar', 'clear',
  'lenge', 'long',
  'hjelpe', 'help',
  'fint', 'fine',
  'visste', 'knew',
  'vite', 'know',
  'forstår', 'understand',
  'under', 'under',
  'noget', 'nothing',
  'hjelp', 'help',
  'skjer', 'happens',
  'okay', 'okay',
  'gir', 'gives',
  'eneste', 'only',
  'heter', 'called',
  'holder', 'hold',
  'bil', 'car',
  'hallo', 'hello',
  'vei', 'road',
  'penger', 'money',
  'siste', 'last',
  'pappa', 'dad',
  'barn', 'children',
  'rundt', 'around',
  'én', 'one',
  'snill', 'kind',
  'tro', 'believe',
  'snart', 'soon',
  'liv', 'life',
  'høre', 'hear',
  'hver', 'each',
  'verden', 'world',
  'tak', 'ceiling',
  'feil', 'error',
  'redd', 'afraid',
  'blitt', 'been',
  'helvete', 'hell',
  'hos', 'with',
  'mamma', 'mom',
  'stor', 'large',
  'lille', 'small',
  'dit', 'there',
  'døde', 'dead',
  'holde', 'keep',
  'herregud', 'omg',
  'prøver', 'samples',
  'visst', 'known',
  'venn', 'friend',
  'heller', 'rather',
  'beste', 'best',
  'husker', 'remember',
  'borte', 'away',
  'hennes', 'her',
  'sikkert', 'certainly',
  'først', 'first',
  'bort', 'away',
  'drar', 'go',
  'like', 'as',
  'ga', 'go',
  'fem', 'five',
  'slutt', 'end',
  'tiden', 'time',
  'gjerne', 'happily',
  'drepe', 'kill',
  'fant', 'found',
  'store', 'large',
  'vekk', 'away',
  'fått', 'received',
  'inne', 'inside',
  'sikker', 'sure',
  'annet', 'others',
  'flere', 'several',
  'oss', 'us',
  'tatt', 'taken',
  'glad', 'happy',
  'hørte', 'heard',
  'neste', 'next',
  'menn', 'Men',
  'våre', 'our',
  'finner', 'find',
  'orden', 'order',
  'navn', 'name',
  'gamle', 'old',
  'fortelle', 'tell',
  'bør', 'should',
  'dø', 'die',
  'alene', 'alone',
  'annen', 'other',
  'nye', 'new',
  'ellers', 'otherwise',
  'venter', 'waiting',
  'synes', 'think',
  'sagt', 'said',
  'måtte', 'must',
  'ny', 'new',
  'venner', 'friends',
  'minutter', 'minutes',
  'liten', 'small',
  'skjedde', 'occurred',
  'betyr', 'means',
  'stille', 'silent',
  'gutt', 'boy',
  'derfor', 'therefore',
  'have', 'have',
  'lenger', 'more',
  'lei', 'sorry',
  'byen', 'town',
  'hatt', 'had',
  'gjennom', 'through',
  'natt', 'night',
  'langt', 'far',
  'klart', 'clear',
  'kjære', 'dear',
  'flott', 'great',
  'ennå', 'yet',
  'fire', 'four',
  'klarer', 'fail',
  'par', 'couple',
  'politiet', 'police',
  'hørt', 'heard',
  'sitt', 'its',
  'unna', 'away',
  'herfra', 'here',
  'slå', 'switch',
  'hjemme', 'home',
  'fort', 'fast',
  'engang', 'even',
  'gode', 'good',
  'føler', 'feel',
  'senere', 'later',
  'skjønner', 'see',
  'dager', 'days',
  'dagen', 'day',
  'meget', 'very',
  'ett', 'one',
  'håper', 'hope',
  'ti', 'ten',
  'faktisk', 'actually',
  'galt', 'wrong',
  'ganger', 'times',
  'pokker', 'heck',
  'nesten', 'almost',
  'tenkte', 'thought',
  'hvilken', 'which',
  'be', 'ask',
  'huset', 'house',
  'jobb', 'job',
  'klare', 'clear',
  'bak', 'behind',
  'snakket', 'spoke',
  'begge', 'both',
  'vise', 'show',
  'slags', 'kind',
  'mens', 'while',
  'fyr', 'guy',
  'ferdig', 'finished',
  'rolig', 'quiet',
  'hodet', 'head',
  'tenk', 'think',
  'lade', 'charge',
  'opp', 'up',
  'virker', 'seems',
  'ei', 'a',
  'jævla', 'damn',
  'ringer', 'rings',
  'hverandre', 'each other',
  'kommet', 'come',
  'skyld', 'fault',
  'stedet', 'instead',
  'jobben', 'job',
  'sine', 'their',
  'bor', 'living',
  'gammel', 'old',
  'prøve', 'sample',
  'hyggelig', 'nice',
  'dårlig', 'bad',
  'drept', 'killed',
  'ord', 'words',
  'vårt', 'our',
  'helst', 'any time',
  'tenker', 'thinking',
  'kvinne', 'female',
  'allerede', 'already',
  'begynner', 'begins',
  'mennesker', 'people',
  'jobber', 'jobs',
  'ligger', 'lies',
  'ønsker', 'wishes',
  'dør', 'door',
  'kun', 'only',
  'grunn', 'because',
  'stå', 'stand',
  'stopp', 'stop',
  'fortell', 'tell',
  'kone', 'wife',
  'øyeblikk', 'moment',
  'slipp', 'release',
  'spiller', 'play',
  'velkommen', 'welcome',
  'del', 'part',
  'jente', 'girl',
  'drepte', 'killed',
  'tenkt', 'thought',
  'riktig', 'right',
  'spise', 'eat',
  'vente', 'wait',
  'seks', 'six',
  'egen', 'own',
  'fortsatt', 'still',
  'glem', 'forget',
  'ganske', 'pretty',
  'sees', 'seen',
  'møte', 'meeting',
  'åh', 'oh',
  'slapp', 'released',
  'fin', 'nice',
  'funnet', 'found',
  'sånt', 'like',
  'nede', 'down',
  'gutten', 'boy',
  'nettopp', 'just',
  'fyren', 'guy',
  'stemmer', 'votes',
  'timer', 'hours',
  'sønn', 'son',
  'herr', 'Mr.',
  'gutter', 'boys',
  'spør', 'ask',
  'selvfølgelig', 'of course',
  'mistet', 'lost',
  'leve', 'live',
  'oppe', 'up',
  'spille', 'play',
  'kaptein', 'captain',
  'sent', 'late',
  'ny', 'new',
  'legg', 'add',
  'sitter', 'sitting',
  'tenke', 'think',
  'jenta', 'girl',
  'gått', 'gone',
  'lett', 'easy',
  'ring', 'call',
  'familien', 'family',
  'pass', 'passport',
  'lang', 'long',
  'måte', 'way',
  'bil', 'car',
  'ringe', 'call',
  'vanskelig', 'difficult',
  'ro', 'tranquility',
  'saken', 'case',
  'kjeft', 'jaw',
  'lever', 'liver',
  'moren', 'mother',
  'videre', 'further',
  'problemer', 'problems',
  'viktig', 'important',
  'ber', 'asks',
  'mat', 'food',
  'nytt', 'new',
  'full', 'full',
  'problem', 'problem',
  'mrs', 'Mrs.',
  'fortalte', 'told',
  'tur', 'tour',
  'fast', 'fixed',
  'treffe', 'hit',
  'ba', 'asked',
  'best', 'best',
  'stort', 'large',
  'fred', 'peace',
  'bruke', 'use',
  'prøv', 'try',
  'mellom', 'between',
  'syns', 'vote',
  'fram', 'forward',
  'hus', 'house',
  'tom', 'empty',
  'fantastisk', 'awesome',
  'redde', 'save',
  'side', 'page',
  'setter', 'sets',
  'dreper', 'kill',
  'hente', 'retrieve',
  'dro', 'went',
  'kjører', 'running',
  'fri', 'free',
  'forsiktig', 'careful',
  'navnet', 'name',
  'uansett', 'regardless',
  'holdt', 'held',
  'fly', 'plane',
  'satt', 'set',
  'utrolig', 'incredible',
  'resten', 'rest',
  'straks', 'immediately',
  'sette', 'set',
  'gal', 'crazy',
  'kaller', 'calls',
  'unge', 'young',
  'egentlig', 'really',
  'tusen', 'thousand',
  'åpne', 'open',
  'imot', 'against',
  'na', 'Features',
  'mest', 'most',
  'fremdeles', 'still',
  'hater', 'hate',
  'vann', 'water',
  'kjøre', 'drive',
  'familie', 'family',
  'kvinner', 'women',
  'utenfor', 'outside',
  'hvert', 'each',
  'skolen', 'school',
  'landet', 'country',
  'spørsmål', 'question',
  'skjedd', 'occurred',
  'prøvde', 'tried',
  'gift', 'married',
  'bror', 'brother',
  'herrer', 'gentlemen',
  'øynene', 'eyes',
  'altså', 'thus',
  'skje', 'spoon',
  'plass', 'space',
  'nødt', 'forced',
  'mulig', 'possible',
  'foran', 'front',
  'enda', 'though',
  'mer', 'more',
  'løp', 'race',
  'uke', 'week',
  'damer', 'ladies',
  'gangen', 'time',
  'lar', 'allows',
  'kona', 'wife',
  'time', 'hour',
  'dritt', 'shit',
  'mindre', 'less',
  'ønske', 'wish',
  'rommet', 'room',
  'vis', 'view',
  'lyst', 'bright',
  'snakk', 'talk',
  'ingen', 'nobody',
  'lite', 'small',
  'lære', 'learn',
  'bruker', 'user',
  'spørre', 'ask',
  'sjanse', 'chance',
  'vondt', 'ache',
  'lykke', 'happiness',
  'aldri', 'never',
  'idiot', 'idiot',
  'nummer', 'number',
  'sove', 'sleep',
  'betale', 'pay',
  'lov', 'law',
  'land', 'country',
  'selvsagt', 'course',
  'passer', 'fits',
  'dum', 'stupid',
  'venstre', 'left',
  'rom', 'room',
  'lover', 'laws',
  'idé', 'Idea',
  'farvel', 'goodbye',
  'begynte', 'started',
  'hendene', 'hands',
  'været', 'weather',
  'ringte', 'called',
  'svært', 'very',
  'huske', 'remember',
  'kjent', 'known',
  'høres', 'sound',
  'lage', 'create',
  'historie', 'history',
  'perfekt', 'perfect',
  'måneder', 'months',
  'små', 'small',
  'skrive', 'write',
  'reise', 'travel',
  'spiser', 'eat',
  'gitt', 'given',
  'ekte', 'real',
  'mente', 'thought',
  'husk', 'remember',
  'laget', 'made',
  'fortsett', 'Continue',
  'våpen', 'weapon',
  'kjør', 'drive',
  'kjøpe', 'buy',
  'jobbet', 'worked',
  'slår', 'beats',
  'svar', 'answer',
  'herre', 'gentleman',
  'hent', 'retrieve',
  'aner', 'reputable',
  'finn', 'find',
  'tidlig', 'early',
  'gifte', 'married',
  'synd', 'sin',
  'igjen', 'again',
  'bryr', 'care',
  'stoppe', 'stop',
  'kjærlighet', 'love',
  'sender', 'submit',
  'skynd', 'hurry',
  'fortalt', 'told',
  'masse', 'mass',
  'bruk', 'use',
  'hånd', 'hand',
  'by', 'city',
  'blod', 'blood',
  'kort', 'card',
  'viser', 'show',
  'sannheten', 'truth',
  'rart', 'strange',
  'kaffe', 'coffee',
  'morsomt', 'funny',
  'hjelper', 'help',
  'uker', 'weeks',
  'millioner', 'million',
  'middag', 'dinner',
  'jobbe', 'work',
  'ung', 'young',
  'stund', 'while',
  'vennen', 'friend',
  'barna', 'children',
  'lager', 'stock',
  'tv', 'television',
  'handler', 'trades',
  'sitte', 'sit',
  'hardt', 'hard',
  'unnskyld', 'excuse',
  'stadig', 'increasingly',
  'legge', 'add',
  'henter', 'retrieves',
  'datter', 'daughter',
  'vakker', 'beautiful',
  'skyte', 'shoot',
  'kjente', 'known',
  'tide', 'time',
  'live', 'live',
  'skyt', 'shoot',
  'tale', 'speech',
  'valg', 'choice',
  'foregår', 'takes place',
  'betaler', 'pay',
  'likte', 'enjoyed',
  'skikkelig', 'properly',
  'slo', 'beat',
  'frem', 'forward',
  'forstå', 'understand',
  'døren', 'door',
  'jenter', 'girls',
  'klokka', 'clock',
  'høyre', 'right',
  'rør', 'tube',
  'begynne', 'start',
  'elsket', 'loved',
  'stikker', 'sticking',
  'sendte', 'sent',
  'telefonen', 'phone',
  'doktor', 'Doctor',
  'lese', 'read',
  'følge', 'follow',
  'general', 'general',
  'drikke', 'drink',
  'gjelder', 'apply',
  'krig', 'war',
  'bo', 'stay',
  'søster', 'sister',
  'jøss', 'geez',
  'krigen', 'war',
  'verre', 'worse',
  'sende', 'send',
  'syk', 'sick',
  'ille', 'bad',
  'skyter', 'shoot',
  'stikke', 'stick',
  'skutt', 'shot',
  'tjeneste', 'service',
  'sak', 'case',
  'klarte', 'managed',
  'vare', 'care',
  'dame', 'lady',
  'døra', 'door',
  'sønnen', 'son',
  'farlig', 'dangerous',
  'forteller', 'says',
  'broren', 'brother',
  'særlig', 'particularly',
  'sist', 'last',
  'måten', 'way',
  'eget', 'own',
  'hvite', 'white',
  'svarte', 'answered',
  'intet', 'nothing',
  'slipper', 'release',
  'gratulerer', 'congratulations',
  'rette', 'right',
  'avtale', 'agreement',
  'likevel', 'nevertheless',
  'pris', 'price',
  'nær', 'close',
  'forbi', 'past',
  'følger', 'follow',
  'fengsel', 'prison',
  'sover', 'sleeping',
  'onkel', 'Uncle',
  'følg', 'follow',
  'leter', 'looking',
  'egne', 'own',
  'drittsekk', 'asshole',
  'natten', 'night',
  'føles', 'feels',
  'bord', 'table',
  'klokken', 'clock',
  'største', 'greatest',
  'flink', 'good',
  'problemet', 'problem',
  'hjertet', 'heart',
  'forklare', 'explain',
  'bekymret', 'concerned',
  'slåss', 'fight',
  'guds', 'god',
  'slippe', 'drop',
  'sint', 'angry',
  'kamp', 'game',
  'åtte', 'eight',
  'baby', 'baby',
  'sekunder', 'seconds',
  'større', 'greater',
  'skriver', 'writes',
  'skjøt', 'extension',
  'ofte', 'often',
  'hjerte', 'heart',
  'sto', 'stood',
  'passe', 'fit',
  'sendt', 'sent',
  'vannet', 'water',
  'endelig', 'finally',
  'skrev', 'wrote',
  'fare', 'hazard',
  'vant', 'won',
  'ærlig', 'honest',
  'spurte', 'asked',
  'skatt', 'tax',
  'sjef', 'chief',
  'enkelt', 'single',
  'dyr', 'animals',
  'født', 'born',
  'glemte', 'forgot',
  'skylder', 'owe',
  'nydelig', 'lovely',
  'spill', 'game',
  'stikk', 'hitch',
  'steder', 'places',
  'falt', 'fell',
  'vinner', 'wins',
  'ansiktet', 'face',
  'døden', 'death',
  'kutt', 'cut',
  'slutte', 'stop',
  'traff', 'hit',
  'høyt', 'high',
  'ordre', 'orders',
  'råd', 'advice',
  'menneske', 'human',
  'stolt', 'proud',
  'reddet', 'saved',
  'umulig', 'impossible',
  'tidligere', 'previously',
  'sjekk', 'check',
  'skade', 'damage',
  'verdens', 'world\'s',
  'mister', 'lose',
  'hvilket', 'which',
  'meter', 'meter',
  'kastet', 'cast',
  'pent', 'nice',
  'historien', 'story',
  'legger', 'puts',
  'kvelden', 'evening',
  'ni', 'nine',
  'glemt', 'forgotten',
  'elske', 'love',
  'beskjed', 'message',
  'leder', 'leader',
  'sjefen', 'boss',
  'overalt', 'everywhere',
  'fikk', 'received',
  'tog', 'train',
  'tingene', 'things',
  'glemme', 'forget',
  'vinne', 'win',
  'hånden', 'hand',
  'ordne', 'arrange',
  'verdt', 'worth',
  'føle', 'feel',
  'lykkelig', 'happy',
  'svart', 'black',
  'fest', 'party',
  'lukk', 'close',
  'flyet', 'plane',
  'fortsette', 'continue',
  'skaffe', 'obtain',
  'stole', 'trust',
  'ræva', 'ass',
  'øl', 'beer',
  'lys', 'light',
  'dumme', 'stupid',
  'hund', 'dog',
  'søt', 'cute',
  'fru', 'Mrs.',
  'lurer', 'wonder',
  'person', 'person',
  'film', 'film',
  'midt', 'middle',
  'barnet', 'child',
  'ære', 'honor',
  'forhold', 'conditions',
  'alvorlig', 'serious',
  'lærer', 'teacher',
  'sju', 'seven',
  'reiser', 'travel',
  'lå', 'lying',
  'kompis', 'mate',
  'kontakt', 'contact',
  'halv', 'half',
  'forelsket', 'love',
  'annerledes', 'different',
  'lege', 'doctor',
  'spesielt', 'special',
  'prate', 'chat',
  'brukte', 'used',
  'flytte', 'move',
  'ønsket', 'wanted',
  'sulten', 'hungry',
  'kontoret', 'office',
  'sov', 'slept',
  'mennene', 'men',
  'smart', 'smart',
  'drøm', 'dream',
  'pistolen', 'pistol',
  'skål', 'cheers',
  'ene', 'one',
  'beskytte', 'protect',
  'løs', 'free',
  'forstått', 'understood',
  'øye', 'eye',
  'trengte', 'needed',
  'miste', 'lost',
  'gjor', 'does',
  'snu', 'turn',
  'absolutt', 'absolute',
  'rolle', 'role',
  'amerika', 'america',
  'drep', 'kill',
  'jaså', 'really',
  'satte', 'continued',
  'frue', 'lady',
  'levende', 'living',
  'lyver', 'lying',
  'lyset', 'light',
  'vanlig', 'common',
  'noensinne', 'ever',
  'kaste', 'throw',
  'pen', 'pretty',
  'filmen', 'movie',
  'jorden', 'Earth',
  'hender', 'hands',
  'opptatt', 'busy',
  'savner', 'miss',
  'dessverre', 'unfortunately',
  'anden', 'duck',
  'kampen', 'game',
  'sprø', 'crazy',
  'kyss', 'kiss',
  'interessant', 'interesting',
  'stoler', 'chairs'
]

const various: string[] = [
  'jeg', 'I',
  'det', 'it',
  'er', 'am',
  'du', 'you',
  'ikke', 'not',
  'en', 'an',
  'og', 'and',
  'i', 'in',
  'har', 'have',
  'vi', 'we',
  'på', 'on',
  'til', 'to',
  'med', 'with',
  'han', 'he',
  'deg', 'you',
  'for', 'for',
  'meg', 'me',
  'hva', 'what',
  'at', 'at',
  'den', 'it',
  'så', 'so',
  'som', 'as',
  'de', 'they',
  'kan', 'can',
  'var', 'was',
  'vil', 'will',
  'av', 'of',
  'skal', 'shall',
  'om', 'if',
  'men', 'but',
  'et', 'an',
  'her', 'here',
  'ja', 'yes',
  'bare', 'only',
  'dere', 'you (plural)',
  'hun', 'she',
  'må', 'must',
  'noe', 'something',
  'ham', 'him',
  'dette', 'this',
  'nei', 'no',
  'nå', 'now',
  'kom', 'come',
  'min', 'my',
  'vet', 'know',
  'der', 'there',
  'din', 'your',
  'ut', 'out',
  'hvor', 'where',
  'da', 'when',
  'fra', 'from',
  'oss', 'us',
  'se', 'see',
  'være', 'be',
  'ha', 'have',
  'dem', 'them',
  'gjør', 'do',
  'igjen', 'again',
  'noen', 'some',
  'kommer', 'come',
  'ta', 'take',
  'ville', 'would',
  'hvis', 'if',
  'alle', 'all',
  'få', 'get',
  'hvorfor', 'why',
  'tror', 'think',
  'går', 'yesterday',
  'alt', 'everything',
  'opp', 'up',
  'sa', 'said',
  'hvordan', 'how',
  'gå', 'go',
  'ingen', 'no',
  'når', 'when',
  'eller', 'or',
  'hvem', 'who',
  'får', 'get',
  'seg', 'themselves',
  'la', 'let',
  'blir', 'becomes',
  'ser', 'see',
  'takk', 'thanks',
  'gjøre', 'do',
  'bli', 'be',
  'bra', 'good',
  'hadde', 'had',
  'si', 'say',
  'denne', 'this',
  'henne', 'her',
  'litt', 'little',
  'inn', 'In',
  'jo', 'yes',
  'etter', 'after',
  'kunne', 'could',
  'vel', 'well',
  'to', 'two',
  'skulle', 'should',
  'ved', 'by',
  'aldri', 'never',
  'hei', 'hi',
  'over', 'over',
  'god', 'good',
  'tilbake', 'back',
  'kanskje', 'perhaps',
  'man', 'one',
  'også', 'also',
  'ble', 'was',
  'nok', 'enough',
  'sier', 'says',
  'selv', 'even',
  'hva', 'what',
  'før', 'before',
  'godt', 'well',
  'ok', 'ok',
  'sammen', 'together',
  'ned', 'down',
  'gi', 'provide',
  'hans', 'his',
  'gang', 'time',
  'dag', 'day',
  'tar', 'takes',
  'mer', 'more',
  'trenger', 'need',
  'mine', 'mine',
  'vært', 'been',
  'mitt', 'my',
  'mye', 'much',
  'helt', 'completely',
  'andre', 'second',
  'sett', 'seen',
  'vær', 'weather',
  'gjorde', 'did',
  'hele', 'throughout',
  'siden', 'ago',
  'komme', 'come',
  'enn', 'than',
  'deres', 'yours (plural)',
  'år', 'year',
  'ditt', 'your',
  'mann', 'husband',
  'hold', 'hold',
  'mr', 'Mr.',
  'mener', 'mean',
  'fikk', 'received',
  'mot', 'against',
  'vent', 'wait',
  'dine', 'your',
  'far', 'father',
  'fordi', 'because',
  'faen', 'fuck',
  'mange', 'many',
  'snakke', 'talk',
  'tre', 'three',
  'hjem', 'home',
  'ting', 'things',
  'gjort', 'made',
  'liker', 'like',
  'sant', 'true',
  'folk', 'people',
  'greit', 'okay',
  'alltid', 'always',
  'rett', 'right',
  'sånn', 'like',
  'tid', 'time',
  'dra', 'go',
  'unnskyld', 'pardon',
  'morgen', 'morning',
  'sir', 'sir',
  'virkelig', 'really',
  'elsker', 'love',
  'bedre', 'better',
  'veldig', 'very',
  'tok', 'took',
  'hit', 'here',
  'vår', 'spring',
  'uten', 'without',
  'mor', 'mother',
  'står', 'stands',
  'kveld', 'evening',
  'død', 'death',
  'burde', 'should',
  'snakker', 'speaks',
  'livet', 'life',
  'finne', 'find',
  'gikk', 'went',
  'sin', 'its',
  'gud', 'god',
  'beklager', 'sorry',
  'trodde', 'thought',
  'ingenting', 'nothing',
  'hør', 'listen',
  'akkurat', 'right',
  'kjenner', 'know',
  'første', 'first',
  'sted', 'place',
  'disse', 'these',
  'ute', 'out',
  'slik', 'so',
  'samme', 'same',
  'klar', 'clear',
  'lenge', 'long',
  'hjelpe', 'help',
  'fint', 'fine',
  'visste', 'knew',
  'vite', 'know',
  'forstår', 'understand',
  'under', 'under',
  'noget', 'nothing',
  'hjelp', 'help',
  'skjer', 'happens',
  'okay', 'okay',
  'gir', 'gives',
  'eneste', 'only',
  'heter', 'called',
  'holder', 'hold',
  'bil', 'car',
  'hallo', 'hello',
  'vei', 'road',
  'penger', 'money',
  'siste', 'last',
  'pappa', 'dad',
  'barn', 'children',
  'rundt', 'around',
  'én', 'one',
  'snill', 'kind',
  'tro', 'believe',
  'snart', 'soon',
  'liv', 'life',
  'høre', 'hear',
  'hver', 'each',
  'verden', 'world',
  'tak', 'ceiling',
  'feil', 'error',
  'redd', 'afraid',
  'blitt', 'been',
  'helvete', 'hell',
  'hos', 'with',
  'mamma', 'mom',
  'stor', 'large',
  'lille', 'small',
  'dit', 'there',
  'døde', 'dead',
  'holde', 'keep',
  'herregud', 'omg',
  'prøver', 'samples',
  'visst', 'known',
  'venn', 'friend',
  'heller', 'rather',
  'beste', 'best',
  'husker', 'remember',
  'borte', 'away',
  'hennes', 'her',
  'sikkert', 'certainly',
  'først', 'first',
  'bort', 'away',
  'drar', 'go',
  'like', 'as',
  'ga', 'go',
  'fem', 'five',
  'slutt', 'end',
  'tiden', 'time',
  'gjerne', 'happily',
  'drepe', 'kill',
  'fant', 'found',
  'store', 'large',
  'vekk', 'away',
  'fått', 'received',
  'inne', 'inside',
  'sikker', 'sure',
  'annet', 'others',
  'flere', 'several',
  'oss', 'us',
  'tatt', 'taken',
  'glad', 'happy',
  'hørte', 'heard',
  'neste', 'next',
  'menn', 'Men',
  'våre', 'our',
  'finner', 'find',
  'orden', 'order',
  'navn', 'name',
  'gamle', 'old',
  'fortelle', 'tell',
  'bør', 'should',
  'dø', 'die',
  'alene', 'alone',
  'annen', 'other',
  'nye', 'new',
  'ellers', 'otherwise',
  'venter', 'waiting',
  'synes', 'think',
  'sagt', 'said',
  'måtte', 'must',
  'ny', 'new',
  'venner', 'friends',
  'minutter', 'minutes',
  'liten', 'small',
  'skjedde', 'occurred',
  'betyr', 'means',
  'stille', 'silent',
  'gutt', 'boy',
  'derfor', 'therefore',
  'have', 'have',
  'lenger', 'more',
  'lei', 'sorry',
  'byen', 'town',
  'hatt', 'had',
  'gjennom', 'through',
  'natt', 'night',
  'langt', 'far',
  'klart', 'clear',
  'kjære', 'dear',
  'flott', 'great',
  'ennå', 'yet',
  'fire', 'four',
  'klarer', 'fail',
  'par', 'couple',
  'politiet', 'police',
  'hørt', 'heard',
  'sitt', 'its',
  'unna', 'away',
  'herfra', 'here',
  'slå', 'switch',
  'hjemme', 'home',
  'fort', 'fast',
  'engang', 'even',
  'gode', 'good',
  'føler', 'feel',
  'senere', 'later',
  'skjønner', 'see',
  'dager', 'days',
  'dagen', 'day',
  'meget', 'very',
  'ett', 'one',
  'håper', 'hope',
  'ti', 'ten',
  'faktisk', 'actually',
  'galt', 'wrong',
  'ganger', 'times',
  'pokker', 'heck',
  'nesten', 'almost',
  'tenkte', 'thought',
  'hvilken', 'which',
  'be', 'ask',
  'huset', 'house',
  'jobb', 'job',
  'klare', 'clear',
  'bak', 'behind',
  'snakket', 'spoke',
  'begge', 'both',
  'vise', 'show',
  'slags', 'kind',
  'mens', 'while',
  'fyr', 'guy',
  'ferdig', 'finished',
  'rolig', 'quiet',
  'hodet', 'head',
  'tenk', 'think',
  'lade', 'charge',
  'opp', 'up',
  'virker', 'seems',
  'ei', 'a',
  'jævla', 'damn',
  'ringer', 'rings',
  'hverandre', 'each other',
  'kommet', 'come',
  'skyld', 'fault',
  'stedet', 'instead',
  'jobben', 'job',
  'sine', 'their',
  'bor', 'living',
  'gammel', 'old',
  'prøve', 'sample',
  'hyggelig', 'nice',
  'dårlig', 'bad',
  'drept', 'killed',
  'ord', 'words',
  'vårt', 'our',
  'helst', 'any time',
  'tenker', 'thinking',
  'kvinne', 'female',
  'allerede', 'already',
  'begynner', 'begins',
  'mennesker', 'people',
  'jobber', 'jobs',
  'ligger', 'lies',
  'ønsker', 'wishes',
  'dør', 'door',
  'kun', 'only',
  'grunn', 'because',
  'stå', 'stand',
  'stopp', 'stop',
  'fortell', 'tell',
  'kone', 'wife',
  'øyeblikk', 'moment',
  'slipp', 'release',
  'spiller', 'play',
  'velkommen', 'welcome',
  'del', 'part',
  'jente', 'girl',
  'drepte', 'killed',
  'tenkt', 'thought',
  'riktig', 'right',
  'spise', 'eat',
  'vente', 'wait',
  'seks', 'six',
  'egen', 'own',
  'fortsatt', 'still',
  'glem', 'forget',
  'ganske', 'pretty',
  'sees', 'seen',
  'møte', 'meeting',
  'åh', 'oh',
  'slapp', 'released',
  'fin', 'nice',
  'funnet', 'found',
  'sånt', 'like',
  'nede', 'down',
  'gutten', 'boy',
  'nettopp', 'just',
  'fyren', 'guy',
  'stemmer', 'votes',
  'timer', 'hours',
  'sønn', 'son',
  'herr', 'Mr.',
  'gutter', 'boys',
  'spør', 'ask',
  'selvfølgelig', 'of course',
  'mistet', 'lost',
  'leve', 'live',
  'oppe', 'up',
  'spille', 'play',
  'kaptein', 'captain',
  'sent', 'late',
  'ny', 'new',
  'legg', 'add',
  'sitter', 'sitting',
  'tenke', 'think',
  'jenta', 'girl',
  'gått', 'gone',
  'lett', 'easy',
  'ring', 'call',
  'familien', 'family',
  'pass', 'passport',
  'lang', 'long',
  'måte', 'way',
  'bil', 'car',
  'ringe', 'call',
  'vanskelig', 'difficult',
  'ro', 'tranquility',
  'saken', 'case',
  'kjeft', 'jaw',
  'lever', 'liver',
  'moren', 'mother',
  'videre', 'further',
  'problemer', 'problems',
  'viktig', 'important',
  'ber', 'asks',
  'mat', 'food',
  'nytt', 'new',
  'full', 'full',
  'problem', 'problem',
  'mrs', 'Mrs.',
  'fortalte', 'told',
  'tur', 'tour',
  'fast', 'fixed',
  'treffe', 'hit',
  'ba', 'asked',
  'best', 'best',
  'stort', 'large',
  'fred', 'peace',
  'bruke', 'use',
  'prøv', 'try',
  'mellom', 'between',
  'syns', 'vote',
  'fram', 'forward',
  'hus', 'house',
  'tom', 'empty',
  'fantastisk', 'awesome',
  'redde', 'save',
  'side', 'page',
  'setter', 'sets',
  'dreper', 'kill',
  'hente', 'retrieve',
  'dro', 'went',
  'kjører', 'running',
  'fri', 'free',
  'forsiktig', 'careful',
  'navnet', 'name',
  'uansett', 'regardless',
  'holdt', 'held',
  'fly', 'plane',
  'satt', 'set',
  'utrolig', 'incredible',
  'resten', 'rest',
  'straks', 'immediately',
  'sette', 'set',
  'gal', 'crazy',
  'kaller', 'calls',
  'unge', 'young',
  'egentlig', 'really',
  'tusen', 'thousand',
  'åpne', 'open',
  'imot', 'against',
  'na', 'Features',
  'mest', 'most',
  'fremdeles', 'still',
  'hater', 'hate',
  'vann', 'water',
  'kjøre', 'drive',
  'familie', 'family',
  'kvinner', 'women',
  'utenfor', 'outside',
  'hvert', 'each',
  'skolen', 'school',
  'landet', 'country',
  'spørsmål', 'question',
  'skjedd', 'occurred',
  'prøvde', 'tried',
  'gift', 'married',
  'bror', 'brother',
  'herrer', 'gentlemen',
  'øynene', 'eyes',
  'altså', 'thus',
  'skje', 'spoon',
  'plass', 'space',
  'nødt', 'forced',
  'mulig', 'possible',
  'foran', 'front',
  'enda', 'though',
  'mer', 'more',
  'løp', 'race',
  'uke', 'week',
  'damer', 'ladies',
  'gangen', 'time',
  'lar', 'allows',
  'kona', 'wife',
  'time', 'hour',
  'dritt', 'shit',
  'mindre', 'less',
  'ønske', 'wish',
  'rommet', 'room',
  'vis', 'view',
  'lyst', 'bright',
  'snakk', 'talk',
  'ingen', 'nobody',
  'lite', 'small',
  'lære', 'learn',
  'bruker', 'user',
  'spørre', 'ask',
  'sjanse', 'chance',
  'vondt', 'ache',
  'lykke', 'happiness',
  'aldri', 'never',
  'idiot', 'idiot',
  'nummer', 'number',
  'sove', 'sleep',
  'betale', 'pay',
  'lov', 'law',
  'land', 'country',
  'selvsagt', 'course',
  'passer', 'fits',
  'dum', 'stupid',
  'venstre', 'left',
  'rom', 'room',
  'lover', 'laws',
  'idé', 'Idea',
  'farvel', 'goodbye',
  'begynte', 'started',
  'hendene', 'hands',
  'været', 'weather',
  'ringte', 'called',
  'svært', 'very',
  'huske', 'remember',
  'kjent', 'known',
  'høres', 'sound',
  'lage', 'create',
  'historie', 'history',
  'perfekt', 'perfect',
  'måneder', 'months',
  'små', 'small',
  'skrive', 'write',
  'reise', 'travel',
  'spiser', 'eat',
  'gitt', 'given',
  'ekte', 'real',
  'mente', 'thought',
  'husk', 'remember',
  'laget', 'made',
  'fortsett', 'Continue',
  'våpen', 'weapon',
  'kjør', 'drive',
  'kjøpe', 'buy',
  'jobbet', 'worked',
  'slår', 'beats',
  'svar', 'answer',
  'herre', 'gentleman',
  'hent', 'retrieve',
  'aner', 'reputable',
  'finn', 'find',
  'tidlig', 'early',
  'gifte', 'married',
  'synd', 'sin',
  'igjen', 'again',
  'bryr', 'care',
  'stoppe', 'stop',
  'kjærlighet', 'love',
  'sender', 'submit',
  'skynd', 'hurry',
  'fortalt', 'told',
  'masse', 'mass',
  'bruk', 'use',
  'hånd', 'hand',
  'by', 'city',
  'blod', 'blood',
  'kort', 'card',
  'viser', 'show',
  'sannheten', 'truth',
  'rart', 'strange',
  'kaffe', 'coffee',
  'morsomt', 'funny',
  'hjelper', 'help',
  'uker', 'weeks',
  'millioner', 'million',
  'middag', 'dinner',
  'jobbe', 'work',
  'ung', 'young',
  'stund', 'while',
  'vennen', 'friend',
  'barna', 'children',
  'lager', 'stock',
  'tv', 'television',
  'handler', 'trades',
  'sitte', 'sit',
  'hardt', 'hard',
  'unnskyld', 'excuse',
  'stadig', 'increasingly',
  'legge', 'add',
  'henter', 'retrieves',
  'datter', 'daughter',
  'vakker', 'beautiful',
  'skyte', 'shoot',
  'kjente', 'known',
  'tide', 'time',
  'live', 'live',
  'skyt', 'shoot',
  'tale', 'speech',
  'valg', 'choice',
  'foregår', 'takes place',
  'betaler', 'pay',
  'likte', 'enjoyed',
  'skikkelig', 'properly',
  'slo', 'beat',
  'frem', 'forward',
  'forstå', 'understand',
  'døren', 'door',
  'jenter', 'girls',
  'klokka', 'clock',
  'høyre', 'right',
  'rør', 'tube',
  'begynne', 'start',
  'elsket', 'loved',
  'stikker', 'sticking',
  'sendte', 'sent',
  'telefonen', 'phone',
  'doktor', 'Doctor',
  'lese', 'read',
  'følge', 'follow',
  'general', 'general',
  'drikke', 'drink',
  'gjelder', 'apply',
  'krig', 'war',
  'bo', 'stay',
  'søster', 'sister',
  'jøss', 'geez',
  'krigen', 'war',
  'verre', 'worse',
  'sende', 'send',
  'syk', 'sick',
  'ille', 'bad',
  'skyter', 'shoot',
  'stikke', 'stick',
  'skutt', 'shot',
  'tjeneste', 'service',
  'sak', 'case',
  'klarte', 'managed',
  'vare', 'care',
  'dame', 'lady',
  'døra', 'door',
  'sønnen', 'son',
  'farlig', 'dangerous',
  'forteller', 'says',
  'broren', 'brother',
  'særlig', 'particularly',
  'sist', 'last',
  'måten', 'way',
  'eget', 'own',
  'hvite', 'white',
  'svarte', 'answered',
  'intet', 'nothing',
  'slipper', 'release',
  'gratulerer', 'congratulations',
  'rette', 'right',
  'avtale', 'agreement',
  'likevel', 'nevertheless',
  'pris', 'price',
  'nær', 'close',
  'forbi', 'past',
  'følger', 'follow',
  'fengsel', 'prison',
  'sover', 'sleeping',
  'onkel', 'Uncle',
  'følg', 'follow',
  'leter', 'looking',
  'egne', 'own',
  'drittsekk', 'asshole',
  'natten', 'night',
  'føles', 'feels',
  'bord', 'table',
  'klokken', 'clock',
  'største', 'greatest',
  'flink', 'good',
  'problemet', 'problem',
  'hjertet', 'heart',
  'forklare', 'explain',
  'bekymret', 'concerned',
  'slåss', 'fight',
  'guds', 'god',
  'slippe', 'drop',
  'sint', 'angry',
  'kamp', 'game',
  'åtte', 'eight',
  'baby', 'baby',
  'sekunder', 'seconds',
  'større', 'greater',
  'skriver', 'writes',
  'skjøt', 'extension',
  'ofte', 'often',
  'hjerte', 'heart',
  'sto', 'stood',
  'passe', 'fit',
  'sendt', 'sent',
  'vannet', 'water',
  'endelig', 'finally',
  'skrev', 'wrote',
  'fare', 'hazard',
  'vant', 'won',
  'ærlig', 'honest',
  'spurte', 'asked',
  'skatt', 'tax',
  'sjef', 'chief',
  'enkelt', 'single',
  'dyr', 'animals',
  'født', 'born',
  'glemte', 'forgot',
  'skylder', 'owe',
  'nydelig', 'lovely',
  'spill', 'game',
  'stikk', 'hitch',
  'steder', 'places',
  'falt', 'fell',
  'vinner', 'wins',
  'ansiktet', 'face',
  'døden', 'death',
  'kutt', 'cut',
  'slutte', 'stop',
  'traff', 'hit',
  'høyt', 'high',
  'ordre', 'orders',
  'råd', 'advice',
  'menneske', 'human',
  'stolt', 'proud',
  'reddet', 'saved',
  'umulig', 'impossible',
  'tidligere', 'previously',
  'sjekk', 'check',
  'skade', 'damage',
  'verdens', 'world\'s',
  'mister', 'lose',
  'hvilket', 'which',
  'meter', 'meter',
  'kastet', 'cast',
  'pent', 'nice',
  'historien', 'story',
  'legger', 'puts',
  'kvelden', 'evening',
  'ni', 'nine',
  'glemt', 'forgotten',
  'elske', 'love',
  'beskjed', 'message',
  'leder', 'leader',
  'sjefen', 'boss',
  'overalt', 'everywhere',
  'fikk', 'received',
  'tog', 'train',
  'tingene', 'things',
  'glemme', 'forget',
  'vinne', 'win',
  'hånden', 'hand',
  'ordne', 'arrange',
  'verdt', 'worth',
  'føle', 'feel',
  'lykkelig', 'happy',
  'svart', 'black',
  'fest', 'party',
  'lukk', 'close',
  'flyet', 'plane',
  'fortsette', 'continue',
  'skaffe', 'obtain',
  'stole', 'trust',
  'ræva', 'ass',
  'øl', 'beer',
  'lys', 'light',
  'dumme', 'stupid',
  'hund', 'dog',
  'søt', 'cute',
  'fru', 'Mrs.',
  'lurer', 'wonder',
  'person', 'person',
  'film', 'film',
  'midt', 'middle',
  'barnet', 'child',
  'ære', 'honor',
  'forhold', 'conditions',
  'alvorlig', 'serious',
  'lærer', 'teacher',
  'sju', 'seven',
  'reiser', 'travel',
  'lå', 'lying',
  'kompis', 'mate',
  'kontakt', 'contact',
  'halv', 'half',
  'forelsket', 'love',
  'annerledes', 'different',
  'lege', 'doctor',
  'spesielt', 'special',
  'prate', 'chat',
  'brukte', 'used',
  'flytte', 'move',
  'ønsket', 'wanted',
  'sulten', 'hungry',
  'kontoret', 'office',
  'sov', 'slept',
  'mennene', 'men',
  'smart', 'smart',
  'drøm', 'dream',
  'pistolen', 'pistol',
  'skål', 'cheers',
  'ene', 'one',
  'beskytte', 'protect',
  'løs', 'free',
  'forstått', 'understood',
  'øye', 'eye',
  'trengte', 'needed',
  'miste', 'lost',
  'gjor', 'does',
  'snu', 'turn',
  'absolutt', 'absolute',
  'rolle', 'role',
  'amerika', 'america',
  'drep', 'kill',
  'jaså', 'really',
  'satte', 'continued',
  'frue', 'lady',
  'levende', 'living',
  'lyver', 'lying',
  'lyset', 'light',
  'vanlig', 'common',
  'noensinne', 'ever',
  'kaste', 'throw',
  'pen', 'pretty',
  'filmen', 'movie',
  'jorden', 'Earth',
  'hender', 'hands',
  'opptatt', 'busy',
  'savner', 'miss',
  'dessverre', 'unfortunately',
  'anden', 'duck',
  'kampen', 'game',
  'sprø', 'crazy',
  'kyss', 'kiss',
  'interessant', 'interesting',
  'stoler', 'chairs'
]